### ISSUE TITLE
Update README to reflect analysis sections

### ISSUE THREAD

**Issue by percyfal** [NBISweden/assemblyeval-smk#6]
Analyses should be defined by analysis section, e.g., 

```
analysis/test:
  label: test
  description: >-
    this is a test
  assembly_ids: ["A", "B"]
  transcript_ids: ["cds"]
  tools:
    genecovr: true
```

This is not documented well.
